version: '3.3'
services:
  postgresql:
    build: ./psql
    ports:
     - '5432:5432'
    volumes:
      - ./psql/db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    environment:
      POSTGRES_USER: bplibapp
      POSTGRES_DB: bp
  server:
    build: ./server
    volumes:
      - ./server:/server
    ports:
      - '1877:1877'
    depends_on:
      - postgresql
    environment:
            DATABASE_URL: postgres://bplibapp@postgresql:5432/bp
  client: 
    build: ./client
    volumes:
      - ./client/src:/client/src
    ports: 
      - '3000:3000'
    links:
      - 'server:server'
